# Generated by Django 4.1.7 on 2023-05-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_team_project_project_team_alter_task_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color',
        ),
    ]
