# Generated by Django 4.1.7 on 2023-06-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_team_project_project_team_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color',
        ),
    ]
