# Generated by Django 4.1.7 on 2023-05-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('incomplete', 'incomplete')], default='incomplete', max_length=10),
        ),
    ]
